# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_vyos:
    working_directory: ~/vyos-docker
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Make it executable"
          command: |
            chmod +x build_vyos.sh
      # Commands run in a Linux virtual machine environment
      - run:
          name: "Build Docker image"
          command: |
            ./build_vyos.sh unibaktr https://downloads.vyos.io/release/legacy/$(cat VERSION)/vyos-$(cat VERSION)-amd64.iso
      - run:
          name: "Push Docker image"
          command: |
            docker image ls
            docker tag vyos:latest vyos:$(cat VERSION)
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push unibaktr/vyos:$(cat VERSION)
            docker push unibaktr/vyos:latest

workflows:
  build:
    jobs:
      - build_vyos
#          filters:
#              tags:
#                only: /.*/


      # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1

#      steps:
#        - checkout

#
